Repository mexili/cssify, pull requests merged in 2021-02, with the labels that each got.

#17 Added loading GIF to the GET CSS button
  client/package-lock.json
  client/src/assets/images/loading.gif
  client/src/components/Playground/Playground.jsx
Labels: user=theshubhagrwl:score=50

#19 Fix title
  client/public/icon.svg
  client/public/index.html
Labels: user=theshubhagrwl:score=25

#21 Feature bug fix
  .gitignore
  README.md
  backend/.npmrc
  backend/package-lock.json
  backend/package.json
  backend/server.js
  client/package-lock.json
  client/package.json
  client/src/components/Playground/Playground.jsx
Labels: user=nimit2801:score=100
